thundra-io/thundra-agent-nodejs

- CHANGELOG.md
- package-lock.json
- package.json
- src/plugins/trace.js
- src/thundra-wrapper.js
- test/plugins/trace.test.js
- `functionARN`,`logGroupName`,`logStreamName`,`requestId` fields are added to trace properites
- Trace data should show response if error type is HTTP error.
> Collect Lambda related properties with trace plugin

- CHANGELOG.md
- package.json
- src/plugins/trace.js
- test/plugins/trace.test.js
Add `timeout` field to trace properties
> Add timeout field to trace properties

- src/Constants.ts
- src/opentracing/instrument/Instrumenter.ts
- src/plugins/Trace.ts
- src/plugins/config/IntegrationConfig.ts
- src/plugins/config/TraceConfig.ts
- src/plugins/integrations/AWSIntegration.ts
- src/plugins/integrations/HttpIntegration.ts
- src/plugins/integrations/MySQL2Integration.ts
- src/plugins/integrations/PostgreIntegration.ts
- src/plugins/integrations/RedisIntegration.ts
Also integrations are enabled by default now.
> Enable instrumentation hooks before trace plugin initializes

- package-lock.json
- package.json
- src/Constants.ts
- src/index.ts
- src/opentracing/Recorder.ts
- src/opentracing/Span.ts
- src/opentracing/Tracer.ts
- src/plugins/AwsXRay.ts
- src/plugins/Log.ts
- src/plugins/Metric.ts
- src/plugins/Trace.ts
- src/plugins/Utils.ts
- src/plugins/config/AwsXRayConfig.ts
- src/plugins/config/ThundraConfig.ts
- src/plugins/integrations/AWSIntegration.ts
- src/plugins/integrations/HttpIntegration.ts
- src/plugins/integrations/MySQL2Integration.ts
- src/plugins/integrations/PostgreIntegration.ts
- src/plugins/integrations/RedisIntegration.ts
- src/plugins/listeners/AwsXRayThundraSpanListener.ts
- src/plugins/listeners/ThundraSpanListener.ts
- test/plugins/aws.xray.span.listener.test.js
- test/plugins/aws.xray.test.js
- test/plugins/trace.test.js
- webpack.config.js
Also added missing tags to Http and AWS and DB integrations.
> AWS XRay Integration

- package.json
> release from jenkins

- src/plugins/integrations/AWSIntegration.ts
Added try catch around `injectTraceLink` so that any kind of serialization error can happen during the generation of the trace links do not fails the lambda.
> Add try catch around "injectTraceLinks"

- src/plugins/integrations/HttpIntegration.ts
http.statusCode tag added to InvocationSupport in HttpIntegration.
> [THN-2008] http.statusCode implementation for invocation

- src/ThundraWrapper.ts
- src/plugins/Invocation.ts
- src/plugins/integrations/HttpIntegration.ts
- src/plugins/utils/Utils.ts
Incorrect Http.statusCode tag removed from HttpIntegration and added to Invocation.
> Thn 2008 http status code for invocation

- src/plugins/integrations/HttpIntegration.ts
Git merge failed to detect the removal of the statusCode line from HttpIntegration on PR #144. Related line is removed in this PR.
> Incorrect line removed from HttpIntegration

- package.json
> Fix release-it git.tagName format

- README.md
- package.json
- src/Constants.ts
- src/config/ConfigMetadata.ts
- src/config/ConfigNames.ts
- src/init/InitManager.ts
- src/init/Initializers.ts
- src/plugins/config/TraceConfig.ts
- src/wrappers/WebWrapperUtils.ts
- src/wrappers/express/ExpressExecutor.ts
- src/wrappers/express/ExpressWrapper.ts
- src/wrappers/hapi/HapiExecutor.ts
- src/wrappers/hapi/HapiWrapper.ts
- test/mock-server/hapi/index.js
- test/mocks/mocks.js
- test/wrappers/hapi/hapi-wrapper.test.js
> Add `Hapi.js` instrumentation capability

- src/Constants.ts
- src/Reporter.ts
- test/reporter.fail.test.js
- test/reporter.test.js
> Add http timeout to reporter

- src/integrations/MongoDBIntegration.ts
- test/integrations/mongodb.integration.test.js
Add mongodb version 4.x support
> Add mongodb version 4.x support

- src/wrappers/foresight/lib/jest/ModuleLoader.ts
- src/wrappers/foresight/lib/jest/ThundraJestEnvironment.ts
Add config check for wrapping transform process
> Add config check for wrapping transform process

- src/config/ConfigMetadata.ts
- src/config/ConfigNames.ts
- src/utils/HTTPUtils.ts
- src/wrappers/lambda/LambdaHandlerWrapper.ts
Added "THUNDRA_AGENT_HTTP_ERROR_IGNORED_STATUS_CODES" variable for ignoring specified http status coded to be marked as an error
> Added "THUNDRA_AGENT_HTTP_ERROR_IGNORED_STATUS_CODES" variable

- src/wrappers/lambda/LambdaEventUtils.ts
- src/wrappers/lambda/LambdaExecutor.ts
Add 'routeKey' and 'rawPath' check for Apigateway v2
> Add 'routeKey' and 'rawPath' check for Apigateway v2

- src/Constants.ts
- src/application/ApplicationManager.ts
- src/context/ExecutionContext.ts
- src/utils/Utils.ts
- src/wrappers/WebWrapperUtils.ts
- src/wrappers/express/ExpressWrapper.ts
- src/wrappers/foresight/ForesightWrapperUtils.ts
- src/wrappers/foresight/context/ForesightContextProvider.ts
- src/wrappers/foresight/context/TestCaseExecutionContext.ts
- src/wrappers/foresight/context/TestSuiteExecutionContext.ts
- src/wrappers/hapi/HapiWrapper.ts
- src/wrappers/koa/KoaWrapper.ts
- test/wrappers/hapi/hapi-wrapper.test.js
Add ApplicationInfo data to ExecutionContext for support multiple wrapper structure(or nested wrapper)
> Add ApplicationInfo data to ExecutionContext for support multiple wrapper structure(or nested wrapper)

- README.md
- package-lock.json
- package.json
- src/Constants.ts
- src/config/ConfigMetadata.ts
- src/config/ConfigNames.ts
- src/integrations/GoogleCloudCommonIntegration.ts
- src/integrations/GoogleCloudPubSubIntegration.ts
- src/utils/HTTPUtils.ts
- src/wrappers/google/pubsub/SubscriptionExecutor.ts
- test/integrations/gcloud.common.integration.test.js
- test/integrations/gcloud.pubsub.integration.test.js
- test/wrappers/google/pubsub/subscription-wrapper.test.js
> Google BigQuery integration

- src/Constants.ts
- src/index.d.ts
- src/index.ts
- src/utils/Utils.ts
- src/wrappers/generic/GenericExecutor.ts
- src/wrappers/generic/GenericWrapper.ts
- test/wrappers/generic/generic-wrapper.test.js
> Generic Function Wrapper

- src/config/ConfigMetadata.ts
- src/config/ConfigNames.ts
- src/integrations/ESIntegration.ts
- test/integrations/es.integration.test.js
- test/integrations/es.legacy.integration.test.js
Add bulk request body content to ES span
> Add bulk request body content to ES span

- .github/workflows/release.yml
- package.json
> GH workflow release package

- src/wrappers/foresight/index.ts
Require 'require-in-the-middle' on runtime
> Require 'require-in-the-middle' on runtime

- src/integrations/AWSv3Integration.ts
Remove shallow copy on command input object for fix propagation issue
> Remove shallow copy on command input object for fix propagation issue

- src/bootstrap/lambda/index.js
Remove Thundra init from lambda bootstrap file
> Remove Thundra init from lambda bootstrap file

- src/wrappers/foresight/lib/jest/ThundraJestEnvironment.ts
> Jest version 28.x support
